'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1008
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ProjetBib.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1382724660_Calender() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1382724660_Calender", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1390669295_103747() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1390669295_103747", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1390669295_1037471() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1390669295_1037471", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1390669339_69542() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1390669339_69542", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1390705980_103703() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1390705980_103703", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1392521557_book() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1392521557_book", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1392521557_book1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1392521557_book1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1392521618_group_half_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1392521618_group_half_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1392521618_group_half_add1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1392521618_group_half_add1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1392521633_24_book_red_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1392521633_24-book-red-add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1392521672_address_book2_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1392521672_address-book2-delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1392521763_172618() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1392521763_172618", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1392521789_48785() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1392521789_48785", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1392521813_6008() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1392521813_6008", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1392521813_60081() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1392521813_60081", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1392521813_60082() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1392521813_60082", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1392521889_db_update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1392521889_db_update", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1392521889_db_update1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1392521889_db_update1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1392521914_Sync() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1392521914_Sync", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1392521944_49911() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1392521944_49911", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1393035400_sign_in() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1393035400_sign-in", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calendar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calendar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property compte() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("compte", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_biblio_poly_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_biblio_poly_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
